ALTER TABLE cadastro ADD COLUMN email VARCHAR(255);
ALTER TABLE cadastro ADD COLUMN senha VARCHAR(255);
ALTER TABLE cadastro ADD COLUMN cep VARCHAR(8);
ALTER TABLE cadastro ADD COLUMN endereco VARCHAR(255);
ALTER TABLE cadastro ADD COLUMN bairro VARCHAR(255);
ALTER TABLE cadastro ADD COLUMN estado VARCHAR(2);
ALTER TABLE cadastro ADD COLUMN contato VARCHAR(100);
